### PR TITLE
Use WebActivatorEx to register VPP from App_Start

### PR DESCRIPTION
**Pull request by mycroes**
If this is OK I can update the sample projects. Not sure how to build the NuGet package though, building it using the spec got me a package without the actual library.

### CODE REVIEW

**Comment by mycroes** [comment]
Is it me or is this pushed to NuGet straight from AppVeyor without your consent?

**Comment by mycroes** [comment]
Issue #13

**Comment by mcintyre321** [comment]
Um yes it pushes without my consent, due to a badly configured appveyor
project, I'll fix that tomorrow .. oops.

Does that package that was produced work ok?

**Comment by mycroes** [comment]
Just tested, works as expected. Has the DLL and the startup file.

**Pull request merged**
